### PR TITLE
Set select query result total to first pass total

### PR DESCRIPTION
**Pull request by rtaket**
The second pass for the query sets the Total to the result count. Instead, the total from the first pass should be used.

### CODE REVIEW

**Comment by dannychenmsft** [comment]
I'd like to know more about the bug here.  And, can you add a unit test for this condition.

**Comment by vScottLouvau** [comment]
I pair coded this with Ryley. The issue is that for single partition tables only (I think) we're returning the count instead of the total as the total with the query. That's because the second pass query (with the IDs to return only) is setting the total and we never copy it from the first pass query.

Adding a new test is a good idea. We verified it passes the other ones (though there are parts of the workflow in Compute which expect result.Total to be for the current query, so it has to be set late in Compute or afterward).

**Comment by dannychenmsft** [comment]
I'm sure this change is fine but I still don't understand the bug.  How can the total be computed correctly for multiple partitions but not for 1 partition?  Scott -- if it is easier, you can just explain it to me later tonight.

**Comment by vScottLouvau** [comment]
I've investigated further.

We have a test for this specific scenario (ask for less than the total number of items and verify the count and total are correct). However, the test is run only for a multiple partition table and directly on a single partition. The multi partition case works because SelectContext.Merge() uses the Pass1Total, and the Partition case passes because Partition never calls OnBeforeQuery, so the select doesn't run as two-pass.

Ryley, if you change TableTests.Table_All to this, you'll get a failure which should be fixed with your change:
        [TestMethod]
        public void Table_All()
        {
            // Try table tests with a two partition table (to validate merge)
            ITable_All(() => new Table("Sample", 75000));

            // Try table tests with a one partition table (to validate merge isn't required)
            ITable_All(() => new Table("Sample", 50000));
        }

Investigation Details:

If you only ask for the ID column, you wouldn't see this issue because:
SelectQuery.ChooseItems:160 -
// If this is already an ID only query, just run it directly
            if (this.Columns.Count == 1 && this.Columns[0].Equals(idColumnName))
            {
                return;
            }

If you have a multi-partition table, it works because:
SelectContext.Merge:474:
if (this.Pass1Results == null)
                {
                    mergedResult.Total = totalFound;
                }
                else
                {
                    mergedResult.Total = this.Pass1Results.Total;
                }

So, we missed fixing the total for the case where there's one partition and thus no merge. We should be able to remove the "use Pass 1 total" in Merge here with Ryley's fix, which will make one and multiple partition cases exactly the same.

**Pull request merged**
